require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: '2.6'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'

Naming/FileName:
  Exclude:
    - 'lib/synthetic-ruby.rb'

Layout/LineLength:
  Max: 120

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
